services:
  - type: web
    name: RAUSHAN
    plan: free
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: bash -c "python3 server.py & python3 -m RAUSHAN"

    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SUDO_USERS
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: STRING_SESSION1
        sync: false
      - key: MONGO_URL
        sync: false
